# Theme Configuration

# Theme settings
theme:
  current: System  # Light, Dark, System, Custom
  
  # Light theme
  light:
    window: "#f0f0f0"
    window_text: "#000000"
    base: "#ffffff"
    alternate_base: "#f5f5f5"
    tooltip_base: "#ffffdc"
    tooltip_text: "#000000"
    text: "#000000"
    button: "#f0f0f0"
    button_text: "#000000"
    bright_text: "#ff0000"
    link: "#0000ff"
    highlight: "#0078d7"
    highlighted_text: "#ffffff"
  
  # Dark theme
  dark:
    window: "#353535"
    window_text: "#ffffff"
    base: "#191919"
    alternate_base: "#353535"
    tooltip_base: "#353535"
    tooltip_text: "#ffffff"
    text: "#ffffff"
    button: "#353535"
    button_text: "#ffffff"
    bright_text: "#ff0000"
    link: "#2a82da"
    highlight: "#2a82da"
    highlighted_text: "#ffffff"
  
  # Custom theme
  custom:
    window: "#ffffff"
    window_text: "#000000"
    base: "#ffffff"
    alternate_base: "#f5f5f5"
    tooltip_base: "#ffffdc"
    tooltip_text: "#000000"
    text: "#000000"
    button: "#f0f0f0"
    button_text: "#000000"
    bright_text: "#ff0000"
    link: "#007bff"
    highlight: "#007bff"
    highlighted_text: "#ffffff"
    accent_color: "#007bff"
    background_color: "#ffffff"
    text_color: "#000000"

# Editor settings
editor:
  font: Consolas
  font_size: 12
  line_numbers: true
  syntax_highlighting: true
  
  # Syntax highlighting colors
  syntax:
    keyword: "#0000ff"
    operator: "#000000"
    brace: "#000000"
    defclass: "#007f7f"
    string: "#007f00"
    string2: "#007f00"
    comment: "#7f7f7f"
    self: "#0000ff"
    numbers: "#007f7f"
